### ISSUE TITLE
Importing react style.css is breaking our own CSS

### ISSUE THREAD

**Issue by charlesBochet** [TypeCellOS/BlockNote#523]
**Describe the bug**
We are using your awesome BlockNote on Twenty and wanted to migrate to the new version: https://github.com/twentyhq/twenty/pull/3517/files

From the release notes:
```
Breaking Changes
Change import "@blocknote/core/style.css"; to import "@blocknote/react/style.css"; if you're using @blocknote/react

This update changes how themes and styles are applied to the editor. This means if you were previously overriding CSS using the componentStyles field in a Theme object, you should convert those styles to CSS rules. See the new theming and styling documentation [here](https://www.blocknotejs.org/docs/theming).
```

However, react/style.css does change the style of non block-note related class, for example: 
`body,html{height:100%}...`

This is an issue as we import it in our project using @blocknote/react/style.css, it completely breaks our page layout.

Before:
<img width="1496" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/12035771/1897b182-8aac-4a03-957d-9ba0a0c2c181">

After:
<img width="1496" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/12035771/1d3d3173-b1e7-476b-b601-b42085090830">

(see that the Sort button for example is broken)

**Comment by YousefED** [comment]
Thanks, we'll look into this asap!

**Comment by YousefED** [comment]
Should be fixed! closed by #535

**Comment by dogfootruler-kr** [comment]
Hello @YousefED,

I'm not sure this issue is fixed in the latest version :(.

Before:
![image](https://github.com/TypeCellOS/BlockNote/assets/3510343/c04323d1-3a6e-4f34-85a9-6c4ca7ede390)

After:
![image](https://github.com/TypeCellOS/BlockNote/assets/3510343/fe69f9f4-df63-4b99-97a6-eb68fe1e0770)

My `yarn.lock` file:
![image](https://github.com/TypeCellOS/BlockNote/assets/3510343/5e22cfcd-12c7-42c3-b913-81c4a28ff023)

Thank you!

**Comment by CarlosVP120** [comment]
It still happens with Shadcn, when importing the styles.css file, it modifies the whole layout :(

**Comment by AIchovy** [comment]
> It still happens with Shadcn, when importing the styles.css file, it modifies the whole layout :(

I also encountered the same problem. Import "@blocknote/mantine/style.css" made some styles of my page layout invalid.

**Comment by YousefED** [comment]
Other report here: https://discord.com/channels/928190961455087667/1216075332524969994/1216075332524969994. @CarlosVP120 @AIchovy could you share a bit more details about what's being reset / changed?

**Comment by matthewlipski** [comment]
I've looked into this and looks like there is a `data-mantine-color-scheme` attribute being added to the `html` root element (see #651, also seems likely to be causing @dogfootruler-kr's styling issue). However, that's the only thing I'm seeing Mantine set on either `html`, `body`, or `#root` so this should solve any remaining problems so I'll create a PR to fix that. In the meantime, I'd appreciate any additional examples of BlockNote/Mantine setting any styles on `html`, `body`, or `#root` elements (screenshots/snippets from browser inspector would be great). Thanks!
